### ISSUE TITLE
Problem: hw wallet not tested on windows

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain-main#135]
check hw-wallet(ledger) is working fine on windows
also make sure that integration test working fine on windows

**Comment by linfeng-crypto** [comment]
started

**Comment by tomtau** [comment]
btw for integration test, GH Actions can run on macOS and Windows Server 2019: https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources -- so our GH action config can be extended to that
(for windows, I guess the blocker would be that nix only works Linux/macOS)

**Comment by yihuang** [comment]
> (for windows, I guess the blocker would be that nix only works Linux/macOS)
not sure if the  Windows Subsystem for Linux will work, https://zaiste.net/os/nix/howtos/install-nix-windows-10/

**Comment by tomtau** [comment]
yeah, that may be a possibility -- just one needs to be sure to build/run the chain-maind.exe instead of the Linux binary (the rest of the integration tests can run in WSL)
