### ISSUE TITLE
Problem: no api to list/query/monitor module accounts

### ISSUE THREAD

**Issue by yihuang** [crypto-com/chain-main#202]
monitor the balances and activities of modules accounts is quite useful to gain insights into the internal state of the chain.

**Comment by tomtau** [comment]
not sure if @devashishdxt was working on something with https://github.com/crypto-com/chain-main/issues/78 ?

**Comment by devashishdxt** [comment]
@yihuang We can use already existing APIs to query information about module accounts if we know their addresses. If not, we can query individual module details like staking pool using `staking query pool` command. Is there something missing?

**Comment by yihuang** [comment]
I guess some api like this:
- list all registered module account addresses.
- query the account address of specified module name.

then we can use bank api to query the balance of the address.

**Comment by yihuang** [comment]
I think not all module account can be queried by individual api, for example I don't find how to query the governance module account which stores all the deposits.

**Comment by devashishdxt** [comment]
> I think not all module balance account can be queried by individual api, for example I don't find how to query the governance module account balance which stores all the deposits.

There is a command to query deposit by `proposal-id`.

**Comment by devashishdxt** [comment]
Also, the names of module accounts are `consts` in code files. For example:

- https://github.com/cosmos/cosmos-sdk/blob/55d7d0c9d11be8cb0425c03d42e37201855d5c67/x/staking/types/pool.go#L12
- https://github.com/cosmos/cosmos-sdk/blob/55d7d0c9d11be8cb0425c03d42e37201855d5c67/x/gov/types/keys.go#L11

**Comment by yihuang** [comment]
> > I think not all module balance account can be queried by individual api, for example I don't find how to query the governance module account balance which stores all the deposits.
> 
> There is a command to query deposit by `proposal-id`.

> > I think not all module balance account can be queried by individual api, for example I don't find how to query the governance module account balance which stores all the deposits.
> 
> There is a command to query deposit by `proposal-id`.

yes, for example I want to check there's no left over coins in the module account, I can sum the deposit coins by iterate the proposals, and check it against the balance of the module account.

**Comment by yihuang** [comment]
> Also, the names of module accounts are `consts` in code files. For example:
> 
> * https://github.com/cosmos/cosmos-sdk/blob/55d7d0c9d11be8cb0425c03d42e37201855d5c67/x/staking/types/pool.go#L12
> * https://github.com/cosmos/cosmos-sdk/blob/55d7d0c9d11be8cb0425c03d42e37201855d5c67/x/gov/types/keys.go#L11

yes, but AFAIK we can't convert them to addresses currently.

**Comment by devashishdxt** [comment]
> yes, for example I want to check there's no left over coins in the governance module account, I can sum the deposit coins by iterate the proposals, and check it against the balance of the module account.

Do you mean something like this?

**Comment by yihuang** [comment]
> > yes, for example I want to check there's no left over coins in the governance module account, I can sum the deposit coins by iterate the proposals, and check it against the balance of the module account.
> 
> Do you mean something like this? https://github.com/cosmos/cosmos-sdk/blob/55d7d0c9d11be8cb0425c03d42e37201855d5c67/x/gov/keeper/invariants.go#L26

yes, looks good, I guess no need to do that check at external then.

**Comment by yihuang** [comment]
https://github.com/cosmos/cosmos-sdk/blob/master/x/auth/types/account.go#L159
it seems module account address is generated deterministically from the name, so no need to query from chain, we can just add some utility in the integration tests.
