### ISSUE TITLE
Problem: cosmovisor not supported

### ISSUE THREAD

**Issue by yihuang** [crypto-com/chain-main#222]
- how new user downloads the old versions of binary.
- how minor versions are upgraded.
- contingency plan in case of total failure of upgrade.

**Comment by leejw51crypto** [comment]
for unix, it's ok,
for windows, binary file may be not available for writing

**Comment by yihuang** [comment]
> for unix, it's ok,
> for windows, binary file may be not available for writing

what do you mean by not available for writing?
