### ISSUE TITLE
Problem: IBC usage not documented

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain-main#227]
it'll be good to try either on our own (two devnet networks) or against some public testnet with IBC enabled -- first in some separate fork/branch; we can then decide whether to merge

**Comment by leejw51crypto** [comment]
yes, i'm wondering how it works with current cosmos atom coin

**Comment by yihuang** [comment]
- add ibc module to chain-maind [DONE]
- extend pystarport's config to support multiple devnets, and config a [relayer](https://github.com/cosmos/relayer) when there's more than one devnet.
