### ISSUE TITLE
Problem: test_upgrade.py fails in make `nix-integration-test`

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain-main#241]
i run this command on linux
make nix-integration-test

error is
[gw0] linux -- Python 3.8.5 /nix/store/x36s3xsl8v0v9wgldjr0bvm3ii3gv06d-python3-3.8.5-env/bin/python3.8

pytestconfig = <_pytest.config.Config object at 0x7fa05e9ba700>
tmp_path_factory = TempPathFactory(_given_basetemp=PosixPath('/run/user/1000/pytest-of-leejw51/pytest-4/popen-gw0'), _trace=<pluggy._tracing.TagTracerSub object at 0x7fa05e8462b0>, _basetemp=PosixPath('/run/user/1000/pytest-of-leejw51/pytest-4/popen-gw0'))

    @pytest.fixture(scope="function")
    def cluster(pytestconfig, tmp_path_factory):
        "override cluster fixture for this test module"
>       yield from cluster_fixture(
            Path(__file__).parent / "configs/default.yaml",
            26900,
            tmp_path_factory,
            quiet=pytestconfig.getoption("supervisord-quiet"),
            post_init=post_init,
            enable_cov=False,
        )

integration_tests/test_upgrade.py:69: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
integration_tests/utils.py:76: in cluster_fixture
    post_init(config, data)
integration_tests/test_upgrade.py:62: in post_init
    edit_chain_program(data / SUPERVISOR_CONFIG_FILE, prepare_node)
integration_tests/test_upgrade.py:32: in edit_chain_program
    ini[section].update(callback(i, old))
integration_tests/test_upgrade.py:47: in prepare_node
    subprocess.run(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

**Comment by leejw51crypto** [comment]
os: mint linux 20

**Comment by yihuang** [comment]
seems to be `no space left on device`.

**Comment by leejw51crypto** [comment]
it's 100% re-produciable in linux, try with linux

**Comment by leejw51crypto** [comment]
cannot reproduce it in latest master
