### ISSUE TITLE
Problem: can't run integration tests in remote machine easily

### ISSUE THREAD

**Issue by yihuang** [crypto-com/chain-main#264]
- After upgrade to big sur, native nix breaks, it would be useful to easily run on linux remote machine(or docker container)
- Run the linux version can also utilize the binary cache uploaded by ci process
- Make the ci-env into independent package makes the env more precise, nix-shell tends to mess with environment variables.

**Comment by leejw51crypto** [comment]
so using docker for nix-shell for tesing

**Comment by yihuang** [comment]
> so using docker + nix-shell for integration testing
> seems ok
> 
> intel mac will be deprecated, so, let's see whether docker will be supported on arm-based macs

the remote builder and runner can be a real machine or vm, not necessary a docker container.
