### ISSUE TITLE
Problem: missing list of ledger hw addresses

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain-main#267]
currently, ledger addresses list are missing like below
chain-maind keys list hw  --ledger --keyring-backend test
Error: unknown flag: --ledger

if possible, include --ledger working in original build

1. add list addresses
chain-maind keys list   --ledger --keyring-backend test

2. add show one address of `hw`
chain-maind keys show hw  --ledger --keyring-backend test

**Comment by linfeng-crypto** [comment]
after you add ledger wallet, the publick key and address will be stored in local db, so no need `--ledger` again, and you can see the ledger wallet info like:

```
- name: hw
  type: ledger
  address: cro1tzhdkuc328cgh2hycyfddtdpqfwwu42yq3qgkr
  pubkey: cropub1addwnpepqw802qz5mvdcchlekqnypgj5vw3hef75yjw6gw6wda823aa0wrdwc7pl4n9
  mnemonic: ""
  threshold: 0
  pubkeys: []
```
