### ISSUE TITLE
Problem: version display is ambiguous

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain-main#270]
currently
version displayed like this
chain-maind version
launchpad-old-97-gccc5a32
change to

for example)
version - build date
chain-1.0.0-20201107

**Comment by tomtau** [comment]
it takes the version from the commit tag -- and the only tag on master is this "launchpad-old"... if you use the released binaries, they should have other versions

**Comment by tomtau** [comment]
https://github.com/crypto-com/chain-main/releases/tag/v0.7.0-rc2
```
% ./chain-maind version
0.7.0-rc2
```

**Comment by tomtau** [comment]
I think the version display is ok... we can tag the master, so there's something more meaningful display for master/development builds -- e.g. when there's a final Stargate release

**Comment by leejw51crypto** [comment]
using commit tag seems good
