### ISSUE TITLE
Problem: uploading to rdbms as an option

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain-main#280]
for each tx processing for the account,
sync account info to rdbms,
information will be
- account  number
- sequence number
- balance

this is useful to cross-check between merkletrie and rdbms.

also will make 3rd party information service very handy to work

it will be implemented with channel  + multi threaded for the performance.
consider spmc pattern

for example)
--eanble_sql_sync "tcp://127.0.0.1:5342" --sql_user "who" --sql_pw "password"

**Comment by tomtau** [comment]
this is better to be done on Tendermint -- there are already issues opened for it + some preliminary work, e.g.: https://github.com/tendermint/tendermint/pull/696/files#diff-7cd27108510ec8cfb4cb50772f62dad12a66e88f99d7a5da916fabba7a82a6abR1
