### ISSUE TITLE
Problem: ibc-transfer not directly tested with chain-maind

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain-main#283]
currently all operations in the integration test are done with the relayer, but it should be possible to just start the relayer and then execute the transfer on the source chain with "chain-maind"

**Comment by yihuang** [comment]
```shell
$ chain-maind tx ibc-transfer transfer transfer demo0channel cro13agmwt5nqzeyhz4j8rg7swx75na8kvwpu7hfds 1000basecro --home data/ibc-0/node0 --node tcp://localhost:26657 --keyring-backend test
Error: cannot unpack Any into ClientState *types.Any: failed unpacking protobuf message from Any
```

**Comment by tomtau** [comment]
interesting, so for `relayer start` vs `relayer tx relay -d` -- is it that the former expects some extra steps to be done (which are done by `relayer` if one uses it directly for transfer)?

**Comment by yihuang** [comment]
> interesting, so for `relayer start` vs `relayer tx relay -d` -- is it that the former expects some extra steps to be done (which are done by `relayer` if one uses it directly for transfer)?

I suspect it's related with some gap between light client update msg, `tx relay -d` will do a light client update immediately before relay the messages.

**Comment by yihuang** [comment]
- in the end, after more trials, I end up with situation that: create tx with chain binary don't work, but create tx with relayer works.
- then after investigate the details of tx construction, find that there's a missed detail, there's a version parsed from chain-id: https://github.com/cosmos/relayer/blob/031ecc2e304af39c789acd0f1b84033d3b8ef4d2/relayer/pathEnd.go#L288
