### ISSUE TITLE
missing file: check-validator-up.sh

### ISSUE THREAD

**Issue by HankFit247** [crypto-com/chain-main#301]
AWS 1-Click but using the instructions here:
https://chain.crypto.com/docs/getting-started/croeseid-testnet.html#step-3-run-everything

"To further check if the validator is signing blocks"
./check-validator-up.sh --tendermint-url https://testnet-croeseid-1.crypto.com:26657 --pubkey $(cat ~/.chain-maind/config/priv_validator_key.json | jq -r '.pub_key.value')

<<insert pup_key address>>

Resulting error:
jq: 1 compile error
-bash: ./check-validator-up.sh: No such file or directory

ubuntu@ip-xx.xx.xx.xx:/chain/.chain-maind$ cd config
ubuntu@ip-xx.xx.xx.xx:/chain/.chain-maind/config$ ll
total 56
drwxr-xr-x 2 crypto crypto  4096 Dec 18 00:59 ./
drwxr-xr-x 4 crypto crypto  4096 Dec 18 00:58 ../
-rw-r--r-- 1 crypto crypto  6031 Nov 16 04:49 app.toml
-rw-r--r-- 1 crypto crypto 15209 Dec 18 00:59 config.toml
-rw-r--r-- 1 crypto crypto 13327 Nov 16 04:48 genesis.json
-rw------- 1 crypto crypto   148 Dec 18 00:59 node_key.json
-rw------- 1 crypto crypto   345 Dec 18 00:58 priv_validator_key.json
ubuntu@ip-172-31-11-118:/chain/.chain-maind/config$

AWS 1-Click
0.7.0-rc2

Fully Synced and Bonded for greater than 24 hours now.

**Comment by HankFit247** [comment]
I found the file on GitHub here:
https://github.com/crypto-com/chain-docs/blob/master/docs/getting-started/assets/signature_checking/check-validator-up.sh

I could sudo nano to recreate it, but not 100% certain where it should be placed.  I'm guessing in /chain/

**Comment by HankFit247** [comment]
I sudo nano'd to create the file manually, now need assistane with setting the proper permissions.

I used:
chmod +x ./check-validator-up.sh

new result:

jq: 1 compile error
./check-validator-up.sh: line 38: $1: unbound variable

**Comment by calvinaco** [comment]
Close this issue as it is related to documenting the usage. An issue has been opened there (https://github.com/crypto-com/chain-docs/issues/80)
