### ISSUE TITLE
Problem: Missing Bech32 Address conversion from PubKey for CLI

### ISSUE THREAD

**Issue by foreseaz** [crypto-com/chain-main#302]
Currently, the validator consensus public key could generate validator operator and account public key, but cannot generate the addresses accordingly:

```
`./chain-maind debug pubkey tcrocnclconspub1zcjduepqp04y2m4qc6hpxrxd446hwzqfy308088xekc4xrhn4qhqpzf4xzkqult4c2`

Address: 259951B2A45F47587CBF8A0F6471D67225336F1F
Hex: 0BEA456EA0C6AE130CCDAD75770809245E779CE6CDB1530EF3A82E00893530AC
JSON (base64): {"type":"tendermint/PubKeyEd25519","value":"C+pFbqDGrhMMza11dwgJJF53nObNsVMO86guAIk1MKw="}
Bech32 Acc: tcropub1zcjduepqp04y2m4qc6hpxrxd446hwzqfy308088xekc4xrhn4qhqpzf4xzkq6yj8pt
Bech32 Validator Operator: tcrocnclpub1zcjduepqp04y2m4qc6hpxrxd446hwzqfy308088xekc4xrhn4qhqpzf4xzkqhpr2l2
Bech32 Validator Consensus: tcrocnclconspub1zcjduepqp04y2m4qc6hpxrxd446hwzqfy308088xekc4xrhn4qhqpzf4xzkqult4c2
```

Request feature: could generate validator operator addresses from CLI `tcrocncl15grftg88l0gdw4mg9t9pwnl0pde2asjzekz0ek`

**Comment by yihuang** [comment]
is this what you want?
```
chain-maind keys show name -a --bech val
```

**Comment by foreseaz** [comment]
@yihuang thanks, will try this out.

**Comment by leejw51crypto** [comment]
this is converting 
from consensus node pub key  (32 bytes, ed25519 )
to address (sha256 hashed, take first 20 bytes)

usually, this key is given automatically,
but when user want to know address from pubkey.

1. provide secp256k1 pubkey(33 bytes)-> address  
2. provide ed25519 pub key (32bytes)-> address 

sha256 hash pubkey , take 20 bytes
display below format together
1. hex
2. bech32

**Comment by tomtau** [comment]
seems this is covered by ` keys show name -a --bech val` but feel free to reopen
