### ISSUE TITLE
Problem: pystarport missing optional pubkey in config

### ISSUE THREAD

**Issue by allthatjazzleo** [crypto-com/chain-main#305]
When using pystarport to generate new genesis, one can specify consensus_key `pub` and `priv` in config.
It would be great to add pubkey as well. As some may use tmkms for initial validator, they are not using `priv_validator_key.json`

**Comment by yihuang** [comment]
supported by field "consensus_key".

**Comment by allthatjazzleo** [comment]
```
      # consensus_key:
      #   priv:
      #   pub:
```
putting dummy `priv` doesn't work when you only have valid `pub`.
when `chain-maind` run `gentx`, it will directly use the pubkey derived from `priv_key` in `priv_validator_key.json` instead of using the literal `pub_key` in `priv_validator_key.json`.

So, for one who only know pub_key in bech32 format better provide optional pubkey field for pystarport
@yihuang
