### ISSUE TITLE
Problem: RPC errors after 900k blocks

### ISSUE THREAD

**Issue by HankFit247** [crypto-com/chain-main#310]
AWS 1-Click here.  Running into a couple of minor issues, all of which have started more consistently after we hit 900k blocks.

Occasionally when staking, I get RPC errors.  Generally I just run the command again, and it sticks.

I just ran Sudo Update and Sudo Upgrade, then double checked to ensure I have the latest blocks and Validator is still signing blocks.

**Comment by allthatjazzleo** [comment]
@HankFit247 
Do you encounter this issue with state-sync?

**Comment by HankFit247** [comment]
@allthatjazzleo 

I beleive the answer is yes, as I used the AWS 1-Click instructions.  Process still took 24 hours to get fully sync'd.
https://chain.crypto.com/docs/getting-started/testnet-aws-1click.html#step-3-running-a-full-node

If you can provide a command to double cgeck, to see if state-sync is enabled, that would be helpful.

**Comment by HankFit247** [comment]
@allthatjazzleo 

From my config.toml

#######################################################
###         State Sync Configuration Options        ###
#######################################################
[statesync]
# State sync rapidly bootstraps a new node by discovering, fetching, and restoring a state machine
# snapshot from peers instead of fetching and replaying historical blocks. Requires some peers in
# the network to take and serve state machine snapshots. State sync is not attempted if the node
# has any local state (LastBlockHeight > 0). The node will have a truncated block history,
# starting from the height of the snapshot.
enable = true



#######################################################
###       Fast Sync Configuration Connections       ###
#######################################################
[fastsync]

# Fast Sync version to use:
#   1) "v0" (default) - the legacy fast sync implementation
#   2) "v1" - refactor of v0 version for better testability
#   2) "v2" - complete redesign of v0, optimized for testability & readability
version = "v0"

**Comment by allthatjazzleo** [comment]
@HankFit247 state-sync is enabled from your config
For current testnet `testnet-croeseid-1`, the state-sync has an issue which will be fixed in `testnet-croeseid-2`.

**Comment by tomtau** [comment]
it seems this issue was related to a bug in the older Tendermint pre-release, so should be OK now on the upgraded testnet (v0.8), but feel free to reopen if you encounter this issue again
