### ISSUE TITLE
Problem: Delegation:  not enough available signers, after 900k blocks

### ISSUE THREAD

**Issue by HankFit247** [crypto-com/chain-main#311]
Generally I just run the command again, and it sticks.  But it's now happening far more frequently, and not resolving.

Sometimes I will get Block "0" but it has a hashtx.  I can see via the 
Example:
https://chain.crypto.com/explorer/tx/07F49213597054771311AA5436AE2573BA4E6DD566AD2149490E012D4B67A5BE

**Comment by HankFit247** [comment]
@tomtau  yes. Sorry, I could not locate my original post.

AWS 1-Click

ubuntu@ip-xx.xx.xx.xx:~$ ./chain-maind tx distribution withdraw-rewards tcrocncl16yzcz3ty94awr7nr2txek9dp2klp2av9vh437s \

--from Default --chain-id "testnet-croeseid-1"
--gas-prices 0.1basetcro
--commission
Enter keyring passphrase:

{"body":{"messages":[{"@type":"/cosmos.distribution.v1beta1.MsgWithdrawDelegatorReward","delegator_address":"tcro1hvtwyzp22j0y8fw5t9anyd4d39pswmxqqq0967","validator_address":"tcrocncl16yzcz3ty94awr7nr2txek9dp2klp2av9vh437s"},{"@type":"/cosmos.distribution.v1beta1.MsgWithdrawValidatorCommission","validator_address":"tcrocncl16yzcz3ty94awr7nr2txek9dp2klp2av9vh437s"}],"memo":"","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[],"fee":{"amount":[{"denom":"basetcro","amount":"20000"}],"gas_limit":"200000","payer":"","granter":""}},"signatures":[]}

confirm transaction before signing and broadcasting [y/N]: y

{"height":"0","txhash":"3B3B70931F5E0C36B70998B8DB714E38A604E341D80A919E9E1C50E187CAE29A","codespace":"sdk","code":4,"data":"","raw_log":"**wrong number of signers**; expected **[BB16E2082A549E43A5D4597B3236AD8943076CC0 D1058145642D7AE1FA6352CD9B15A155BE157585]**, got 1: unauthorized","logs":[],"info":"","gas_wanted":"200000","gas_used":"0","tx":null,"timestamp":""}

ubuntu@ip-xx.xx.xx.xx:~$

Didn't start till we hit 900K blocks.
Happening far more frequently now.

Here is an additional pairing that I received when reattempting the transaction.
**[BB16E2082A549E43A5D4597B3236AD8943076CC0 8C0262BA5A9B38FA205E6B1D7A568A8C0309C4CE]**

**Comment by tomtau** [comment]
it seems this issue was related to a bug in the older Tendermint pre-release, so should be OK now on the upgraded testnet (v0.8), but feel free to reopen if you encounter this issue again
