### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Aggrord09** [crypto-com/chain-main#321]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tomtau** [comment]
this doesn't provide any details of what the "bug" was -- see https://github.com/crypto-com/chain-main/blob/master/CONTRIBUTING.md#feature-requests-and-bug-reports
