### ISSUE TITLE
missing: check-validator-up.sh

### ISSUE THREAD

**Issue by HankFit247** [crypto-com/chain-main#327]
AWS 1-Click.

Version 1 I created the file, and all worked fine then.

Version 2 I once again created the file, and still cannot sign blocks.

https://github.com/crypto-com/chain-docs/blob/master/docs/getting-started/assets/signature_checking/check-validator-up.sh

**Comment by tomtau** [comment]
it seems to have been updated in chain-docs by @allthatjazzleo https://github.com/crypto-com/chain-docs/pull/89 -- but feel free to reopen
