### ISSUE TITLE
Problem: empty genesis validation function

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain-main#333]
in genesis.go the `Validate()` function only returns "nil" -- the function should be updated to check the genesis state consistency or the comment should be added to explain why it doesn't perform any validations

**Comment by devashishdxt** [comment]
The reason for this is that there is no genesis state in supply module to validate (https://github.com/crypto-com/chain-main/blob/master/proto/supply/v1beta/genesis.proto). I'll add a comment for this.
