### ISSUE TITLE
Problem: potentially unneeded, deprecated and legacy functions in use

### ISSUE THREAD

**Issue by tomtau** [crypto-com/chain-main#338]
> A number of deprecated and legacy functions are still in use throughout the codebase.

> AminoCodec in the file x/supply/types/codec.go (this also applies to the file x/chainmain/types/codec.go). These are called by the method RegisterLegacyAminoCodec of AppModuleBasic in x/supply/module.go. Similarly, consider removing functions that are not used, such as the method LegacyQuerierHandler() of AppModule defined in x/chainmain/module.go. Most of the functions in x/chainmain/module.go are either empty, or perform default behavior. Similarly, the function InitGenesis() in x/chainmain/genesis.go is empty and the function ExportGenesis() of the same file returns the default genesis. The function RegisterRoutes() in x/chainmain/client/rest/rest.go is also empty.

**Comment by devashishdxt** [comment]
@tomtau @yihuang Should we get rid of legacy APIs from `chainmain` and `supply` modules?

**Comment by tomtau** [comment]
Yes, if possible -- I commented on that in the original PR: https://github.com/crypto-com/chain-main/pull/258#discussion_r520259675
the legacy API for SDK modules should still be registered though -- I think they are being used @calvinaco @calvinlauco
