### ISSUE TITLE
Problem: app doesn't save keys

### ISSUE THREAD

**Issue by Kwaskoff** [crypto-com/chain-main#340]
**Describe the bug**
chain-maind creates, but doesn't save keys

**To Reproduce**
1. I do this step https://chain.crypto.com/docs/getting-started/croeseid-testnet.html#step-3-run-everything
2. Check keys by `./chain-maind keys show Default`
3. No keys 🤷‍♂️

**Screenshots**
![image](https://user-images.githubusercontent.com/15308024/103572227-4bb7ae80-4edd-11eb-932e-26ef28b9cb40.png)

**Desktop (please complete the following information):**
 - OS: [xubuntu 20.04];[linux mint 20]
 - Version [v0.8.0-rc1]

**Comment by yihuang** [comment]
The os native keyring don't work in your case, you can try `--keyring-backend=file`.

**Comment by Kwaskoff** [comment]
> --keyring-backend=file

yep! Thx. This is different key saving in GUI version of linux
