### ISSUE TITLE
Problem:  Different PubKeys

### ISSUE THREAD

**Issue by HankFit247** [crypto-com/chain-main#364]
AWS 1-Click
0.8.1-crossfire

Why would my PubKeys' be different?

cat ~/.chain-maind/config/priv_validator_key.json | jq -r '.pub_key.value'
DETmr82581NZU3Q04NsZdOTZM85FRnrsXpDiwqOcLlQ=

Where as:
https://cc.smartstake.io/val/3
states IA2sj0LoIZDV0r9P2K2WDlnq2Ho9YBn4z2vZl2k9dA0=

**Comment by tomtau** [comment]
@allthatjazzleo @calvinaco I think in AWS 1-Click, tmkms is used, so it's the pubkey from tmkms, not the "priv_validator_key.json" -- @HankFit247 can you confirm that?

**Comment by HankFit247** [comment]
Resolved with a recover.
