### ISSUE TITLE
Problem: ledger not working in NETWORK=testnet

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain-main#371]
on mainnet, it's ok
how to reproduce)
export NETWORK=testnet
make build
make install
./chain-maind  keys add hw --keyring-backend test --ledger

example)
 chain-maind  keys add hw --keyring-backend test --ledger
override the existing name hw [y/N]: y
Error: address  rejected
Usage:

**Comment by tomtau** [comment]
not a bug -- Ledger app fixes the coin type: https://chain.crypto.com/docs/wallets/ledger.html#generate-address
